---
# SPDX-FileCopyrightText: 2025 The MalInt development team
#
# SPDX-License-Identifier: CC0-1.0
name: Check formatting of the project
on: [push, pull_request]
permissions:
  contents: read
jobs:
  yamlfix:
    name: Check formatting with yamlfix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.13'
          enable-cache: true
      - name: Check YAML formatting
        run: uvx yamlfix -v --check --exclude pnpm-lock.yaml .
  biome:
    name: Check formatting with biome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install biome
        uses: biomejs/setup-biome@v2
        with:
          version: 2.3
      - name: Check Typescript and JSON formatting
        run: biome format .
  mdformat:
    name: Check formatting with mdformat
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.13'
          enable-cache: true
      - name: Check Markdown formatting
        run: uvx mdformat --check .
